
create or replace view sandbox-financeiro-471714.ds_trusted_contabil.vw_base_contabil_gerencial as 
select
safe_cast(CD_EMPRESA as int64) as cd_empresa, 
safe_cast(CONTA_CONTABIL as int64) as cd_conta_contabil,
DESC_CONTABIL as ds_conta_contabil,
COD_CC as cd_centro_custo,
Centro_de_custo as ds_centro_custo,
DATE_ADD(DATE '1899-12-30', INTERVAL SAFE_CAST(COMPETENCIA AS INT64) DAY) AS dt_competencia,
LOTE as cd_lote,
DOCUMENTO as cd_documento,
NO_TITULO ds_titulo,
RAZAO ds_razao,
ORIGEM ds_origem,
safe_cast(VALOR as float64) vl_valor,
CD_FORNECEDOR cd_fornecedor,
FORNECEDOR ds_fornecedor,
FORNECEDOR_AJUSTADO ds_fornecedor_ajustado,
CD_CLIENTE cd_cliente,
CLIENTE ds_cliente,
CH_CONCILIACAO cd_consiliacao,
safe_cast(SEQUENCIA as int64) sequencia,
PROJETO ds_projeto,
FILIAL cd_filial,
DESC_CC,
VRS nm_versao,
TIPO nm_tipo,
MES mes,
ANO ano,
k1 ds_classificacao_n1,
k2 ds_classificacao_n2,
k3 ds_classificacao_n3,
pct_2020 ds_pacote,
cg nm_conta_gerencial,
Motivo_da_Reclassificacao ,
Solicitado_por nm_solicitado_por,
Realizado_por nm_realizado_por,
Data_da_Reclassificacao dt_reclassificacao,
VERTICAL ds_vertical,
oneoffs ds_oneoffs,
dh_carga

from sandbox-financeiro-471714.ds_raw_contabil.tb_base_contabil_gerencial